#!/bin/sh
# install latest versoin according to http://asdf-vm.com/guide/getting-started.html#_2-download-asdf . Then:

asdf plugin-add elixir https://github.com/asdf-vm/asdf-elixir.git
asdf plugin-add erlang https://github.com/asdf-vm/asdf-erlang.git
asdf plugin-add ruby https://github.com/asdf-vm/asdf-ruby.git
asdf plugin-add nodejs https://github.com/asdf-vm/asdf-nodejs.git

# reload bash's command cache -- run this after installing versions
hash -r
