#!/usr/bin/env ruby

require 'socket'
def desktop?
  Socket.gethostname == 'simon-linuxdesktop'
end

HOME = `echo ~`.chomp

files = `ls -a ~/dev/dotfiles`
          .split
          .reject {|f| f.length < 3}
          .reject {|f| f == '.git'}
          .select {|f| f[0] == '.'}

puts "symlinking #{files.join(', ')}"

files.each do |file|
  `ln -fs ~/dev/dotfiles/#{file} ~`
end

`mkdir -p ~/.config/i3/`
`mkdir -p ~/.config/i3status/`
`mkdir -p ~/.config/termite/`
`ln -fs ~/dev/dotfiles/i3_config ~/.config/i3/config`
`ln -fs ~/dev/dotfiles/i3status_config ~/.config/i3status/config`
`ln -fs ~/dev/dotfiles/mimeapps.list ~/.local/share/applications/mimeapps.list`
`ln -fs ~/dev/dotfiles/termite_config ~/.config/termite/config`
# xdg-utils deletes and recreates ~/.config/mimeapps.list when it writes to it, which will break symbolic links
`cp ~/dev/dotfiles/mimeapps.list ~/.config/mimeapps.list`

# vim
`mkdir -p ~/.vim/pack/`
`mkdir -p ~/.vim/_backup/`
`mkdir -p ~/.vim/_temp/`
`mkdir -p ~/.vim/undodir/`
`mkdir -p ~/.vim/after/plugin/`
`ln -fs ~/dev/dotfiles/vimrc_after.vim ~/.vim/after/plugin/vimrc_after.vim`
`rm ~/.vim/pack/synced`
# -T stops ln treating synced/ as a directory rather than a target name
`ln -fs -T ~/dev/dotfiles/vim_plugins/ ~/.vim/pack/synced`
`rm ~/.vim/colors`
`ln -fs -T ~/dev/dotfiles/vim_colors/ ~/.vim/colors`

if desktop?
  `cat noedit i3_config_base i3_config_desktop > i3_config`
  `cat noedit i3status_config_base i3status_config_desktop > i3status_config`
else
  `cat noedit i3_config_base i3_config_laptop > i3_config`
  `cat noedit i3status_config_base i3status_config_laptop > i3status_config`
end
