#!/usr/bin/env ruby

require 'socket'

def desktop?
  Socket.gethostname == 'simon-linuxdesktop'
end
def thinkpad?
  Socket.gethostname == 'simon-thinkpad'
end
def xps?
  # TODO when on xps replace with hostname check
  !thinkpad? && !desktop?
end

HOME = `echo ~`.chomp

files = `ls -a ~/dev/dotfiles`
          .split
          .reject {|f| f.length < 3}
          .reject {|f| f == '.git'}
          .select {|f| f[0] == '.'}

puts "symlinking #{files.join(', ')}"

files.each do |file|
  `ln -fs ~/dev/dotfiles/#{file} ~`
end

`mkdir -p ~/.config/i3/`
`mkdir -p ~/.config/sway/`
`mkdir -p ~/.config/waybar/`
`mkdir -p ~/.config/i3status/`
`mkdir -p ~/.config/alacritty/`
`mkdir -p ~/.config/dunst/`
`mkdir -p ~/.config/xkb/symbols/`
`mkdir -p ~/.config/nvim/`
`ln -fs ~/dev/dotfiles/init.lua ~/.config/nvim/init.lua`
`ln -fs ~/dev/dotfiles/i3_config ~/.config/i3/config`
`ln -fs ~/dev/dotfiles/sway_config ~/.config/sway/config`
`ln -fs ~/dev/dotfiles/waybar_config ~/.config/waybar/config`
`ln -fs ~/dev/dotfiles/waybar_style.css ~/.config/waybar/style.css`
`ln -fs ~/dev/dotfiles/i3status_config ~/.config/i3status/config`
`ln -fs ~/dev/dotfiles/mimeapps.list ~/.local/share/applications/mimeapps.list`
`ln -fs ~/dev/dotfiles/alacritty.toml ~/.config/alacritty/alacritty.toml`
`ln -fs ~/dev/dotfiles/dunstrc ~/.config/dunst/dunstrc`
`ln -fs ~/dev/dotfiles/default-golang-pkgs ~/.default-golang-pkgs`
# xdg-utils deletes and recreates ~/.config/mimeapps.list when it writes to it, which will break symbolic links
`cp ~/dev/dotfiles/mimeapps.list ~/.config/mimeapps.list`
if !File.exist?('/etc/apt/sources.list.d/custom.list')
  `sudo ln -fs /home/simon/dev/dotfiles/apt-custom-sources.list /etc/apt/sources.list.d/custom.list`
end

# vim
`mkdir -p ~/.vim/pack/`
`mkdir -p ~/.vim/_backup/`
`mkdir -p ~/.vim/_temp/`
`mkdir -p ~/.vim/undodir/`
`mkdir -p ~/.vim/after/plugin/`
`ln -fs ~/dev/dotfiles/vimrc_after.vim ~/.vim/after/plugin/vimrc_after.vim`
`rm ~/.vim/pack/synced`
# -T stops ln treating synced/ as a directory rather than a target name
`ln -fs -T ~/dev/dotfiles/vim_plugins/ ~/.vim/pack/synced`
`rm ~/.vim/colors`
`ln -fs -T ~/dev/dotfiles/vim_colors/ ~/.vim/colors`

if desktop?
  `cat noedit i3_config_base i3_config_desktop > i3_config`
  `cat noedit i3status_config_base i3status_config_desktop > i3status_config`
  `cat noedit i3_config_base sway_config_desktop > sway_config`
  `ln -fs ~/dev/dotfiles/ginit-desktop.vim ~/.config/nvim/ginit.vim`
else
  `cat noedit i3_config_base i3_config_laptop > i3_config`
  `cat noedit i3_config_base sway_config_laptop > sway_config`
  `ln -fs ~/dev/dotfiles/xkb_custom_layout ~/.config/xkb/symbols/gb`
  `ln -fs ~/dev/dotfiles/ginit-laptop.vim ~/.config/nvim/ginit.vim`
`ln -fs ~/dev/dotfiles/kanshi_config ~/.config/kanshi/config`
  # `ln -fs ~/.XmodmapForLaptopKeyboard ~/.Xmodmap`
  if thinkpad?
    `cat noedit i3status_config_base i3status_config_thinkpad i3status_config_laptop > i3status_config`
  else
    `cat noedit i3status_config_base i3status_config_xps i3status_config_laptop > i3status_config`
  end
end
